apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
  labels:
    app: auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
        - name: auth-server-image
          image: registry.gitlab.com/gaia-x/data-infrastructure-federation-services/authenticationauthorization/auth-service-image
          imagePullPolicy: Always
          env:
            - name: AAS_TSA_DURATION
              value: "100000"
            - name: SPRING_PROFILES_ACTIVE
              value: test-suite
            - name: SERVER_HOST
              value: 78.138.66.89
          ports:
            - name: "http"
              containerPort: 9000
            - name: "https"
              containerPort: 9443
          resources: {}
      restartPolicy: Always

#          readinessProbe:
#            httpGet:
#              path: "/ssi/qr/test"
#              port: 9000

#        resources: {}
#        terminationMessagePath: /dev/termination-log
#        terminationMessagePolicy: File
#      dnsPolicy: ClusterFirst
#      restartPolicy: Always
#      terminationGracePeriodSeconds: 30
