apiVersion: v1
kind: Secret
metadata:
  name: auth-server-keys-secret
type: Opaque
stringData:
  iat: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJmMGUzNzY0Mi0zYWIzLTQ2NWItODcyYi1kNmZkMTljOTcwOWQifQ.eyJleHAiOjAsImlhdCI6MTY1MjI3MTgwNiwianRpIjoiMGIyNWU0ZTYtMmMxNi00MTFlLTkyMDctY2UwNDcyYTNkMGUxIiwiaXNzIjoiaHR0cDovL2tleS1zZXJ2ZXI6ODA4MC9yZWFsbXMvZ2FpYS14IiwiYXVkIjoiaHR0cDovL2tleS1zZXJ2ZXI6ODA4MC9yZWFsbXMvZ2FpYS14IiwidHlwIjoiSW5pdGlhbEFjY2Vzc1Rva2VuIn0.V8X5dKASZPa4SlzfbPfAwxf7oIuqYp9px6Dvfg7EJDc     
  jwk: 96ec048e-c640-4cfd-bc82-6571810a9d0f
