server:
  host: auth-server
  port: 9000

aas:
  tsa:
    url: http://trustservice/api
  iam:
    base-uri: http://key-server:8080
    client-iat: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJkMDc0OWE1MS04YTJmLTRkOWQtYTk2YS1jNzhjYTQyZmNlMTUifQ.eyJleHAiOjAsImlhdCI6MTY1Mjc4NTk2MCwianRpIjoiMjRjYjI2N2ItMmUwZi00YzQ5LTg0MGItYWUyNjQyNDg1OTU4IiwiaXNzIjoiaHR0cDovL2tleS1zZXJ2ZXI6ODA4MC9yZWFsbXMvZ2FpYS14IiwiYXVkIjoiaHR0cDovL2tleS1zZXJ2ZXI6ODA4MC9yZWFsbXMvZ2FpYS14IiwidHlwIjoiSW5pdGlhbEFjY2Vzc1Rva2VuIn0.IWu2-nP4ojXMxLn9B9lz7c-YQ-LDGhI9XUKdoa0f2tA
    client-registration-uri: /realms/gaia-x/clients-registrations/openid-connect
    ttl: 10m
    clients:
      oidc:
        id: aas-app-oidc
        secret: "{noop}secret"
        redirect-uri: ${aas.iam.base-uri}/realms/gaia-x/broker/ssi-oidc/endpoint
      siop:
        id: aas-app-siop
        secret: "{noop}secret2"
        redirect-uri: ${aas.iam.base-uri}/realms/gaia-x/broker/ssi-siop/endpoint    