server:
  port: 8090

spring:
  profiles:
    active: default
  application:
    name: auth-service

security:
  oauth2:
    client:
      clientId:
      clientSecret:
      accessTokenUri:
      userAuthorizationUri:
      clientAuthenticationScheme: form

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /api/docs
    enabled: true
