server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
      
aas:
  oidc:
    issuer: https://auth-server.gxfs.dev
          
logging:
  level:
    root: INFO
    tsclaims: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    eu.gaiax.difs.aas: INFO
