server:
  port: 9000

#spring:
#  security:
#    oauth2:
#      client:
#        client-id: aas-app
#        client-secret: 8ngxjnfoywTFd5MR8HZkLKslQpfuffKE
#        registration:
#          keycloak:
##            client-id: demo-app
#            client-id: aas-app
#            scope: 
#              - openid
##              - profile
