server:
  host: auth-server
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
aas:
  tsa:
    url: https://gaiax.vereign.com/tsa/policy
  iam:
    base-uri: http://key-server:8080
  id-token:
    ttl: 5m
      
logging:
  level:
    root: INFO
    tsclaims: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    eu.gaiax.difs.aas: INFO
