server:
  port: 9000
  tomcat:
    mbeanregistry:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

aas:
  cache:
    size: 0
    ttl: 1m
  iam:
    base-uri: http://key-server:8080
    iat:
      secret: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJhMWYzMTI2MS1iMTUyLTQ3ZWUtOTcyMi02OThjYTMxNjk1MGYifQ.eyJleHAiOjAsImlhdCI6MTY3Nzg1MTA4NCwianRpIjoiMzVkYzlkNDEtMjg5OC00YmI2LWI2MDAtNmFlMTQ2MGU3ZjM1IiwiaXNzIjoiaHR0cDovL2tleS1zZXJ2ZXI6ODA4MC9yZWFsbXMvZ2FpYS14IiwiYXVkIjoiaHR0cDovL2tleS1zZXJ2ZXI6ODA4MC9yZWFsbXMvZ2FpYS14IiwidHlwIjoiSW5pdGlhbEFjY2Vzc1Rva2VuIn0.VpDxKCCwmQor-zoJnYlzYDqxxdugBoIu4aj7A8sXsZ0
#  token:
#    ttl: 1m
  tsa:
    url: http://trustservice/api
    repo: aisbl
    group: example
    version: 1.0
    action: evaluation
    delay: 100
    duration: 1000
    request:
      count: 1
    statuses:
      GetLoginProofResult: ACCEPTED
      GetIatProofResult: ACCEPTED

logging:
  level:
    root: INFO
    tsclaims: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    eu.gaiax.difs.aas: DEBUG
