server:
  host: auth-server
  port: 9000
  servlet:
    session:
      timeout: 10m
  http2:
    enabled: true
  ssl:
    enabled: true
    protocol: TLS
    key-store-type: PKCS12
    key-alias:
    key-store:
    key-store-password:

spring:
  profiles:
    active: default
  application:
    name: auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${server.host}:${server.port}
          jwk-set-uri: https://${server.host}:${server.port}/oauth2/jwks
  messages:
    encoding: ISO-8859-1
management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /api/docs
    enabled: true

aas:
  tsa:
    url: http://trustservice/api
    repo: aisbl
    group: aisbl
    version: 1.0
    action: evaluate
    delay: 500 # in milliseconds
    duration: 5000 # in milliseconds
  iam:
    base-uri: http://key-server:8080
    client-registration-uri: /auth/realms/gaia-x/clients-registrations/openid-connect
    realm: gaia-x
    client-iat: "{noop}iat"
    ttl: 10m
    clients:
      oidc:
        id: aas-app-oidc
        secret: "{noop}secret"
        redirect-uri: ${aas.iam.base-uri}/realms/gaia-x/broker/ssi-oidc/endpoint
      siop:
        id: aas-app-siop
        secret: "{noop}secret2"
        redirect-uri: ${aas.iam.base-uri}/realms/gaia-x/broker/ssi-siop/endpoint
  scopes:
    openid:
      - sub
      - iss
      - auth_time
    profile:
      - name
      - given_name
      - family_name
      - middle_name
      - preferred_username
      - gender
      - birtdate
      - updated_at
    email:
      - email
      - email_verified

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    eu.gaiax.difs.aas: DEBUG
