aas:
  iam:
    client-iat: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIxZWQxZGM4Mi05MGVkLTQ3M2QtOWMyMi0xOWFlZGEzYTA1YTkifQ.eyJleHAiOi0xNzgwNTE1NTY4LCJpYXQiOjE2NTA1MzgxMjgsImp0aSI6IjMzMjE3YTY2LTgyNGMtNGMzZS04NGU0LTNiNzVmYWNiNDYxYyIsImlzcyI6Imh0dHA6Ly9rZXktc2VydmVyOjgwODAvcmVhbG1zL2dhaWEteCIsImF1ZCI6Imh0dHA6Ly9rZXktc2VydmVyOjgwODAvcmVhbG1zL2dhaWEteCIsInR5cCI6IkluaXRpYWxBY2Nlc3NUb2tlbiJ9.w3NQ9m1R_AeFi9x-yAfx3fQWeZhfR-Cy5mvi_S1z-JI
