server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

#aas:
#  iam:
#    base-uri: https://key-server.gxfs.dev          
#  oidc:
#    issuer: https://auth-server.gxfs.dev
#  tsa:
#    url: https://gaiax.vereign.com/tsa/policy
    
logging:
  level:
    root: INFO
    tsclaims: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    eu.gaiax.difs.aas: INFO
