application:
  localTrustServiceClient:
    policyMocks:
      GetLoginProofInvitation:
        requestId: to-be-overwritten
        link: test-link
      GetLoginProofResult:
        iss: test-iss
        sub: test-sub
        claim1: test-claim1
      GetIatProofInvitation:
        requestId: to-be-overwritten
      GetIatProofResult:
        iss: test-iss
        sub: test-sub
        claim1: test-claim1
