server:
  port: 8091
spring:
  security:
    oauth2:
      client:
        clientId: aas-app
        clientSecret: 8ngxjnfoywTFd5MR8HZkLKslQpfuffKE
        accessTokenUri: https://localhost:8080/login/oauth/access_token
        userAuthorizationUri: https://localhost:8080/login/oauth/authorize
        clientAuthenticationScheme: form