server:
  port: 9000

#spring:
#  security:
#    oauth2:
#      client:
#        client-id: aas-app
#        client-secret: qBhoUVKaqQqD0YVgMiEyq7dYehYPNtmz
#        registration:
#          keycloak:
##            client-id: demo-app
#            client-id: aas-app
#            scope:
#              - openid
##              - profile
