aas:
  iam:
    clients:
       oidc:
         id: aas-app-oidc
         secret: "{noop}secret"
         redirect-uris: 
           - ${aas.iam.base-uri}/realms/gaia-x/broker/ssi-oidc/endpoint
       siop:
         id: aas-app-siop
         secret: "{noop}secret2"
         redirect-uris: 
           - ${aas.iam.base-uri}/realms/gaia-x/broker/ssi-siop/endpoint
       gxfs:
         id: gxfs-demo
#         secret: "{noop}hmi-secret2"
         redirect-uris: 
           - https://demo.gxfs.dev
       portal:
         id: demo-portal
         secret: "{noop}demo-portal"
         redirect-uris: 
           - https://fc-demo-server.gxfs.dev
           - https://fc-server.gxfs.dev
           - http://78.138.66.181:8088/*
  token:
    ttl: 5m
