server:
  port: 8090
  servlet:
    session:
      timeout: 10m

management:
  endpoints:
    web:
      exposure:
        include: "*"
  
spring:
  application:
    name: auth-service
  messages:
    encoding: ISO-8859-1

springdoc:
  api-docs:
    path: /api/docs
    enabled: true

logging:
  level:
    root: INFO
    tsclaims: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    eu.gaiax.difs.aas: INFO
