server:
  port: 9000

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
aas:
  tsa:
    url: http://trustservice/api
  iam:
    base-uri: http://key-server:8080
    client-registration-uri: /auth/realms/gaia-x/clients-registrations/openid-connect
    realm: gaia-x
    client-id: aas-app
    client-iat: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIyYTczZjczNi1hM2FjLTQ2MjAtYTBhZC0zZDQzMjQ3OTU0NGEifQ.eyJleHAiOjAsImlhdCI6MTY0ODA0MzQzNCwianRpIjoiYWJhNjFkMjgtMGZiOS00YTk0LWIwNGYtOGE3YmM0NDE5NTllIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9nYWlhLXgiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvcmVhbG1zL2dhaWEteCIsInR5cCI6IkluaXRpYWxBY2Nlc3NUb2tlbiJ9.KWf9DSLKbExyhxKKxH7vkZaInl5MIed9ZhrxK93x5SU
    client-secret: "{noop}secret"
    redirect-uri: http://key-server:8080/realms/gaia-x/broker/ssi-oidc/endpoint