server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
aas:
  iam:
    base-uri: https://key-server.gxfs.dev
#    base-uri: http://key-server:8080
  oidc:
    issuer: https://auth-server.gxfs.dev
#    issuer: http://auth-server:9000
  token:
    ttl: 5m
  tsa:
    url: https://gaiax.vereign.com/tsa
      
logging:
  level:
    root: INFO
    tsclaims: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    eu.gaiax.difs.aas: INFO
