server:
  port: 8090
  servlet:
    session:
      timeout: 10m
  
spring:
  application:
    name: auth-service

logging:
  level:
    root: INFO
    tsclaims: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    eu.gaiax.difs.aas: INFO
