server:
  port: 8090
  servlet:
    session:
      timeout: 5m

aas:
  cache:
    size: 0
    ttl: 5m
  iam:
    base-uri: http://key-server:8080
    clients:
      oidc:
        id: aas-app-oidc
        secret: "{noop}secret"
        redirect-uris: 
          - ${aas.iam.base-uri}/realms/gaia-x/broker/ssi-oidc/endpoint
      siop:
        id: aas-app-siop
        secret: "{noop}secret2"
        redirect-uris: 
          - ${aas.iam.base-uri}/realms/gaia-x/broker/ssi-siop/endpoint
    iat:
      dcr-uri: ${aas.iam.base-uri}/realms/gaia-x/clients-registrations/openid-connect
      redirect-uri: ${aas.oidc.issuer}/*
      secret: "{noop}iat"
  invitation:
    uri: gxfspcm://aries_connection_invitation?
  jwk:
    length: 3072
    secret: 96ec048e-c640-4cfd-bc82-6571810a9d0f
  oidc:
    issuer: http://auth-server:8090
    static-scopes:
  siop:
    clock-skew: 5s 
    issuer: https://self-issued.me/v2
  scopes:
    openid:
      - sub
      - iss
      - auth_time
    profile:
      - name
      - given_name
      - family_name
      - middle_name
      - preferred_username
      - gender
      - birthdate
      - updated_at
    email:
      - email
      - email_verified
  token:
    ttl: 5m
  tsa:
    url: http://trustservice/api
    repo: aisbl
    group: example
    version: 1.0
    action: evaluation
    delay: 500 # in milliseconds
    duration: 5000 # in milliseconds
    request:
      count: 2
    statuses:
      GetLoginProofResult: ACCEPTED
      GetIatProofResult: ACCEPTED

