server:
  port: 8990
spring:
  profiles:
    active: default
  application:
    name: demo-app
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/gaia-x
        registration:
          keycloak:
            client-id: demo-app
            scope: openid
