server:
  port: 8990
spring:
  profiles:
    active: default
  application:
    name: demo-app
  security:
    oauth2:
      client:
        registration:
          demo-app-oidc:
            provider: keycloak
            client-id: demo-app
            client-secret: secret
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://key-server:8080/realms/gaia-x
            jwk-set-uri: http://key-server:8080/realms/gaia-x/protocol/openid-connect/certs
#            issuer-uri: https://key-server.gxfs.dev/realms/gaia-x
#            jwk-set-uri: https://key-server.gxfs.dev/realms/gaia-x/protocol/openid-connect/certs

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG    
    eu.gaiax.difs.aas: DEBUG
