server:
  port: 8990
spring:
  profiles:
    active: default
  application:
    name: demo-app
  security:
    oauth2:
      client:
        registration:
          demo-app-oidc:
            provider: keycloak
            client-id: demo-app
            client-secret: secret
            scope: openid
#            authorization-grant-type: authorization_code
#            redirect-uri: "http://key-server:8080/realms/gaia-x/broker/ssi-oidc/endpoint" 
#            client-name: demo-app-oidc
        provider:
          keycloak:
            issuer-uri: http://key-server:8080/realms/gaia-x

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG    
    eu.gaiax.difs.aas: DEBUG
