server:
  port: 8990
spring:
  profiles:
    active: default
  application:
    name: demo-app
  security:
    oauth2:
      client:
        registration:
          aas-app:
            provider: keycloak
            client-id: aas-app
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://auth-server:8080/auth/realms/gaia-x/broker/ssi-oidc/endpoint"
            scope: openid
            client-name: aas-app
        provider:
          keycloak:
            issuer-uri: http://auth-server:8080/auth/realms/gaia-x

