version: '3.8'

services:

  aas:
    build:
      context: ../service
      dockerfile: Dockerfile
    environment:
      - "SPRING_PROFILES_ACTIVE=${PROFILES_AAS}"
    expose:
      - "9000"
    networks:
      - "gaia-x"
    depends_on:
      - nginx
    restart: unless-stopped

  keycloak:
    container_name: "key-server"
    environment:
      KEYCLOAK_ADMIN: "${KEYCLOAK_ADMIN}"
      KEYCLOAK_ADMIN_PASSWORD: "${KEYCLOAK_ADMIN_PASSWORD}"
      PROXY_ADDRESS_FORWARDING: "${PROXY_ADDRESS_FORWARDING}"

    image: "quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}"
    ports:
      - "8080:8080"
    extra_hosts:
      - "auth-server:host-gateway"
    networks:
      - "gaia-x"
    restart: unless-stopped

    volumes:
      - "../keycloak/providers:/opt/keycloak/providers"
      - "../keycloak/realms:/tmp/import"

    command:
      [
          'start-dev --auto-build',
          '-Dkeycloak.migration.action=import',
          '-Dkeycloak.migration.provider=dir',
          '-Dkeycloak.migration.dir=/tmp/import',
          '-Dkeycloak.migration.strategy=OVERWRITE_EXISTING',
          '-Dkeycloak.profile.feature.upload_scripts=enabled',
          '--log-level=DEBUG,io.quarkus:INFO,liquibase:INFO,org.hibernate:INFO,org.infinispan:INFO,org.keycloak.services.scheduled:INFO,org.keycloak.transaction:INFO'
      ]

  nginx:
    image: nginx:latest
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "9000:9000"
    networks:
      - "gaia-x"

networks:
  gaia-x:
    driver: "bridge"