version: '3.8'

services:

  aas:
    build:
      context: ../service
      dockerfile: Dockerfile
    environment:
      - "SPRING_PROFILES_ACTIVE=${PROFILES_AAS}"
    expose:
      - "9000"
    networks:
      - "gaia-x"
    restart: unless-stopped

  demo:
    build:
      context: ../app
      dockerfile: Dockerfile
    expose:
      - "8990"
    networks:
      - "gaia-x"
    restart: unless-stopped

  keycloak:
    container_name: "key-server"
    environment:
      KEYCLOAK_ADMIN: "${KEYCLOAK_ADMIN}"
      KEYCLOAK_ADMIN_PASSWORD: "${KEYCLOAK_ADMIN_PASSWORD}"

    image: "quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}"
    ports:
      - "8080:8080"
    extra_hosts:
      - "auth-server:host-gateway"
    networks:
      - "gaia-x"
    restart: unless-stopped

    volumes:
      - "../keycloak/src/main/resources/providers:/opt/keycloak/providers"
      - "../keycloak/src/main/resources/realms/import:/tmp/import"

    command:
      [
          'start-dev --auto-build',
          '-Dkeycloak.migration.action=import',
          '-Dkeycloak.migration.provider=dir',
          '-Dkeycloak.migration.dir=/tmp/import',
          '-Dkeycloak.migration.strategy=OVERWRITE_EXISTING',
      ]

  nginx:
    image: nginx:latest
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    depends_on:
      - aas
      - demo
      - keycloak
    ports:
      - "4000:4000"
      - "5000:5000"
    networks:
      - "gaia-x"

networks:
  gaia-x:
    driver: "bridge"