version: '3.8'

services:

  aas:
    build:
      context: ../service
      dockerfile: Dockerfile
    container_name: "auth-server"
    environment:
      - "SPRING_PROFILES_ACTIVE=${PROFILES_AAS}"
    ports:
      - "9000:9000"
    networks:
      - "gaia-x"
    restart: unless-stopped

  app:
    build:
      context: ../app
      dockerfile: Dockerfile
    container_name: "test-server"
    environment:
      - "SPRING_PROFILES_ACTIVE=${PROFILES_AAS}"
    ports:
      - "8990:8990"
    networks:
      - "gaia-x"
    restart: unless-stopped

  keycloak:
    container_name: "key-server"
    environment:
      KEYCLOAK_ADMIN: "${KEYCLOAK_ADMIN}"
      KEYCLOAK_ADMIN_PASSWORD: "${KEYCLOAK_ADMIN_PASSWORD}"
      PROXY_ADDRESS_FORWARDING: "${PROXY_ADDRESS_FORWARDING}"
    image: "quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}"
    ports:
      - "8080:8080"
    extra_hosts:
      - "auth-server:host-gateway"
    networks:
      - "gaia-x"
    restart: unless-stopped

    volumes:
      - "../keycloak/providers:/opt/keycloak/providers"
      - "../keycloak/realms_local:/tmp/import"

    command:
      [
          'start-dev --auto-build',
          '-Dkeycloak.migration.action=import',
          '-Dkeycloak.migration.provider=dir',
          '-Dkeycloak.migration.dir=/tmp/import',
          '-Dkeycloak.migration.strategy=OVERWRITE_EXISTING',
          '-Dkeycloak.profile.feature.upload_scripts=enabled',
          '--log-level=DEBUG,io.quarkus:INFO,liquibase:INFO,org.hibernate:INFO,org.infinispan:INFO,org.keycloak.services.scheduled:INFO,org.keycloak.transaction:INFO,io.netty.buffer.PoolThreadCache:INFO,org.keycloak.models.sessions.infinispan:INFO'
      ]

networks:
  gaia-x:
    driver: "bridge"