apiVersion: v1
kind: Service
metadata: 
  name: test-server-service
  labels: 
    app: test-server
spec: 
  ports: 
#    - port: 53582
    - name: "8990"
      port: 8990
      targetPort: 8990
  selector: 
    app: test-server
#  type: LoadBalancer
  type: ClusterIP
#status:
#  loadBalancer: {}
