apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  configmapName: {{ .Values.config.configmapName }}
  configmapNamespace: {{ .Values.config.configmapNamespace }}