apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-spring-app-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
   application-k8s.yml: | 
            {{- toYaml .Values.properties | nindent 5}}
