apiVersion: v1
kind: PersistentVolume
metadata:
  name: aas-postgres-volume
  labels:
    app: aas-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/shared-data/postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aas-postgres-claim
  labels:
    app: aas-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi